# Generated by Django 4.1.3 on 2022-11-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
